In [ ]:
from sklearn.decomposition import PCA
import pandas as pd
import numpy as np

In [ ]:
data = pd.read_csv("/content/sample_data/california_housing_train.csv")
data

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0
...,...,...,...,...,...,...,...,...,...
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0

In [ ]:
X = data.drop(labels=data.columns[-1],axis=1)

In [ ]:
X

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250
...,...,...,...,...,...,...,...,...
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147

In [ ]:
pca = PCA()

In [ ]:
transformed_X=pca.fit_transform(X)

In [ ]:
transformed_X.shape

(17000, 8)

In [ ]:
proj_X=pd.DataFrame(transformed_X,
             columns=[f"Feature_{x}" for x in range(1,transformed_X.shape[1]+1)])

In [ ]:
proj_X.cov()

,Feature_1,Feature_2,Feature_3,Feature_4,Feature_5,Feature_6,Feature_7,Feature_8
Feature_1,6.077377e+06,1.862755e-11,3.617305e-11,-1.177918e-12,-8.015153e-12,-3.424181e-14,1.284068e-13,-8.553766e-14
Feature_2,1.862755e-11,2.849272e+05,-4.561010e-12,3.711813e-12,1.262453e-12,-4.160380e-13,-2.172215e-14,-1.107509e-14
Feature_3,3.617305e-11,-4.561010e-12,3.035111e+04,-3.760607e-12,-1.600270e-13,-4.130419e-14,1.171712e-14,-1.293431e-14
Feature_4,-1.177918e-12,3.711813e-12,-3.760607e-12,2.621575e+03,-2.568136e-14,-3.948509e-14,9.443250e-15,-6.834987e-15
Feature_5,-8.015153e-12,1.262453e-12,-1.600270e-13,-2.568136e-14,1.363932e+02,3.878956e-15,-1.072565e-15,1.205486e-15
Feature_6,-3.424181e-14,-4.160380e-13,-4.130419e-14,-3.948509e-14,3.878956e-15,8.073986e+00,1.177062e-15,-4.961552e-16
Feature_7,1.284068e-13,-2.172215e-14,1.171712e-14,9.443250e-15,-1.072565e-15,1.177062e-15,2.397131e+00,4.296946e-16
Feature_8,-8.553766e-14,-1.107509e-14,-1.293431e-14,-6.834987e-15,1.205486e-15,-4.961552e-16,4.296946e-16,2.444247e-01

In [ ]:
pca.singular_values_

array([3.21417700e+05, 6.95950997e+04, 2.27142804e+04, 6.67563904e+03,
       1.52267805e+03, 3.70472239e+02, 2.01863382e+02, 6.44590968e+01])

In [ ]:
zerom_X = X-np.mean(X,axis=0)
X.cov()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income
longitude,4.020692,-3.965185,-2.883552,2.054900e+02,60.685329,2.340172e+02,45.974646,-0.059248
latitude,-3.965185,4.568221,0.442652,-1.806526e+02,-62.497196,-2.729633e+02,-61.558579,-0.327506
housing_median_age,-2.883552,0.442652,158.430983,-9.904993e+03,-1700.026828,-4.275002e+03,-1465.311997,-2.784428
total_rooms,205.489998,-180.652575,-9904.992690,4.752169e+06,853059.831387,2.152369e+06,770353.377150,812.729998
total_bedrooms,60.685329,-62.497196,-1700.026828,8.530598e+05,177661.787682,4.263264e+05,158982.941347,-10.853597
population,234.017167,-272.963262,-4275.001960,2.152369e+06,426326.444591,1.317566e+06,401317.218749,-1.396588
households,45.974646,-61.558579,-1465.311997,7.703534e+05,158982.941347,4.013172e+05,147856.277053,5.608393
median_income,-0.059248,-0.327506,-2.784428,8.127300e+02,-10.853597,-1.396588e+00,5.608393,3.641061

In [ ]:
zmX_cov = 1/zerom_X.shape[0]*(np.matmul(zerom_X.T,zerom_X))
zmX_cov

<ipython-input-89-95b320c28f94>:1: FutureWarning: Calling a ufunc on non-aligned DataFrames (or DataFrame/Series combination). Currently, the indices are ignored and the result takes the index/columns of the first DataFrame. In the future , the DataFrames/Series will be aligned before applying the ufunc.
Convert one of the arguments to a NumPy array (eg 'ufunc(df1, np.asarray(df2)') to keep the current behaviour, or align manually (eg 'df1, df2 = df1.align(df2)') before passing to the ufunc to obtain the future behaviour and silence this warning.
  zmX_cov = 1/zerom_X.shape[0]*(np.matmul(zerom_X.T,zerom_X))

,0,1,2,3,4,5,6,7
longitude,4.020456,-3.964952,-2.883383,2.054779e+02,60.681759,2.340034e+02,45.971941,-0.059245
latitude,-3.964952,4.567953,0.442626,-1.806419e+02,-62.493519,-2.729472e+02,-61.554958,-0.327487
housing_median_age,-2.883383,0.442626,158.421663,-9.904410e+03,-1699.926826,-4.274750e+03,-1465.225802,-2.784264
total_rooms,205.477911,-180.641948,-9904.410044,4.751890e+06,853009.651397,2.152242e+06,770308.062246,812.682190
total_bedrooms,60.681759,-62.493519,-1699.926826,8.530097e+05,177651.336989,4.263014e+05,158973.589410,-10.852958
population,234.003402,-272.947206,-4274.750489,2.152242e+06,426301.366564,1.317489e+06,401293.611854,-1.396506
households,45.971941,-61.554958,-1465.225802,7.703081e+05,158973.589410,4.012936e+05,147847.579624,5.608063
median_income,-0.059245,-0.327487,-2.784264,8.126822e+02,-10.852958,-1.396506e+00,5.608063,3.640847

In [ ]:
svd = np.linalg.svd(zmX_cov)

In [ ]:
transformed_X_m = np.matmul(zerom_X,svd[0])

In [ ]:
transformed_X_m

,0,1,2,3,4,5,6,7
0,-2548.462950,-1675.368431,-176.694599,451.797385,-1.794425,3.878558,1.179346,1.492993
1,-4486.293020,-2466.352693,-308.054162,839.231263,-17.610251,3.024562,-1.696091,1.033831
2,2271.258841,-155.221708,14.677030,33.190517,14.830972,4.562708,2.722381,1.760112
3,1465.339874,-328.773036,-23.775044,54.142843,15.831044,4.701464,1.191306,1.843502
4,1456.886292,-208.071528,-23.881561,24.562863,10.580953,4.731190,2.508884,1.770503
...,...,...,...,...,...,...,...,...
16995,639.653398,-289.531050,26.383700,-10.491428,-22.731611,-6.372973,1.339104,-0.009410
16996,366.069656,-78.789431,-58.095235,13.515137,-7.018859,-6.862207,0.440339,-0.038868
16997,57.434978,-184.177704,3.508883,21.144013,10.865868,-7.924719,0.375002,0.481535
16998,32.288309,-130.812676,-16.130231,20.183012,8.996086,-7.988086,1.266766,0.368891
16999,1061.136529,-213.830213,79.679991,4.595604,-22.332635,-6.426407,0.618891,-0.052695

In [ ]:
xv = transformed_X_m.cov()
pd.DataFrame(transformed_X)

,0,1,2,3,4,5,6,7
0,2548.462950,-1675.368431,-176.694599,451.797385,1.794425,-3.878558,-1.179346,1.492993
1,4486.293020,-2466.352693,-308.054162,839.231263,17.610251,-3.024562,1.696091,1.033831
2,-2271.258841,-155.221708,14.677030,33.190517,-14.830972,-4.562708,-2.722381,1.760112
3,-1465.339874,-328.773036,-23.775044,54.142843,-15.831044,-4.701464,-1.191306,1.843502
4,-1456.886292,-208.071528,-23.881561,24.562863,-10.580953,-4.731190,-2.508884,1.770503
...,...,...,...,...,...,...,...,...
16995,-639.653398,-289.531050,26.383700,-10.491428,22.731611,6.372973,-1.339104,-0.009410
16996,-366.069656,-78.789431,-58.095235,13.515137,7.018859,6.862207,-0.440339,-0.038868
16997,-57.434978,-184.177704,3.508883,21.144013,-10.865868,7.924719,-0.375002,0.481535
16998,-32.288309,-130.812676,-16.130231,20.183012,-8.996086,7.988086,-1.266766,0.368891
16999,-1061.136529,-213.830213,79.679991,4.595604,22.332635,6.426407,-0.618891,-0.052695

In [ ]:
pd.DataFrame(transformed_X)==transformed_X_m

           0      1      2      3      4      5      6      7
0      False  False  False  False  False  False  False  False
1      False  False  False  False  False  False  False  False
2      False  False  False  False  False  False  False  False
3      False  False  False  False  False  False  False  False
4      False  False  False  False  False  False  False  False
...      ...    ...    ...    ...    ...    ...    ...    ...
16995  False  False  False  False  False  False  False  False
16996  False  False  False  False  False  False  False  False
16997  False  False  False  False  False  False  False  False
16998  False  False  False  False  False  False  False  False
16999  False  False  False  False  False  False  False  False

[17000 rows x 8 columns]